version: 0.7.{build}-alpha
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache: src/packages
branches:
  only:
    - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: |
    function UpdateProjectVersion([string]$xmlPath, [string]$version)
    {
        $xml = [xml](get-content $xmlPath)
        $propertyGroup = $xml.Project.PropertyGroup | Where { $_.Version}
        $propertyGroup.Version = $version
        $xml.Save($xmlPath)
    }
    UpdateProjectVersion("$env:appveyor_build_folder/src/Lime.Protocol/Lime.Protocol.csproj", "$env:appveyor_build_version")
    UpdateProjectVersion("$env:appveyor_build_folder/src/Lime.Protocol.Serialization/Lime.Protocol.Serialization.csproj", "$env:appveyor_build_version")
    UpdateProjectVersion("$env:appveyor_build_folder/src/Lime.Messaging/Lime.Messaging.csproj", "$env:appveyor_build_version")

- dotnet restore src/Lime.sln
build:
  parallel: true
  project: src/Lime.sln
  verbosity: normal
after_build:
- dotnet pack src/Lime.Protocol/Lime.Protocol.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Lime.Protocol.Serialization/Lime.Protocol.Serialization.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Lime.Messaging/Lime.Messaging.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Lime.Transport.Tcp/Lime.Transport.Tcp.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Lime.Transport.WebSocket/Lime.Transport.WebSocket.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Lime.Transport.Redis/Lime.Transport.Redis.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
test:
  assemblies:    
    - '**\*Tests.dll'
  categories: 
    except:
      - 'Redis'
artifacts:
  - path: '**\Lime*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 0huvVwDjQ/i7FNOrby1sd/KJ1NaSFNOmTh4uUuS/kp7K7W2O3sDdnEeeYz8MwAzb
  skip_symbols: false